name: CI

on: [push, pull_request]

env:
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flutter test
        run: |
          uname -a
          which flutter
          flutter --version
